/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI */

#ifndef _Included_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
#define _Included_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    getVJoyVersion
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_getVJoyVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    isVJoyEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_isVJoyEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    getNumButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_getNumButtons
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    doesDeviceExist
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_doesDeviceExist
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    claimDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_claimDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    releaseDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_releaseDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    resetDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_resetDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI
 * Method:    setButton
 * Signature: (IBZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rmconway_tppm_controllers_vjoy_ffi_VJoyJNI_setButton
  (JNIEnv *, jobject, jint, jbyte, jboolean);

#ifdef __cplusplus
}
#endif
#endif
